### ISSUE TITLE
Random gender info - male / female option please!

### ISSUE THREAD

**Issue by ask10000** [FotoVerite/Faker.js#12]
This one would be a good add
faker.Sex.gender() to get either Male or Female as String.

**Comment by drlukeangel** [comment]
This is super old but it came up in search.. you can do this already.. 
let gender = faker.random.arrayElement([male, female])
since the functions take numbers
let gender =  faker.random.arrayElement([1, 2])
or if you use male female
let genderNum = gender === 'male' ? 0 : 1;
You can close this

**Comment by ask10000** [comment]
Thanks @drlukeangel

**Comment by Shwetabh1** [comment]
FakerJS hasn't explicitly added gender as a function but there are few workarounds:

`let gender = ['Male', 'Female', 'Unknown'];`
`console.log(faker.random.arrayElement(gender));`
`console.log(gender[faker.random.number % gender.length]);`
